### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by XinsongDu** [lemaslab/RUMP#31]

**Comment by thulium1** [comment]
[RUMP Logo.pdf](https://github.com/lemaslab/RUMP/files/4536744/RUMP.Logo.pdf)

**Comment by thulium1** [comment]
If we want to buy it from someone, I found a pretty cool logo. It's only $12
https://www.istockphoto.com/vector/logo-r-letter-monogram-thin-lines-style-gm642923530-116559763

**Comment by XinsongDu** [comment]
@thulium1 Great job! Both of the logos look great! @hballard22 @nishachachad Please work together with Nisha and new members to provide more logo candidates, we may start to vote and select one in the end. Some examples: https://github.com/bionitio-team; https://github.com/phnmnl/container-xcms; https://github.com/hariszaf/pema; https://github.com/mzmine/mzmine3.

Thank you all for your hard work!
